export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  placementTest: '/placement-test',
  levels: '/levels',
  level: (level: string) => `/levels/${level.toLowerCase()}`,
  levelGrammar: (level: string) => `/levels/${level.toLowerCase()}/grammar`,
  levelVocabulary: (level: string) => `/levels/${level.toLowerCase()}/vocabulary`,
  levelReading: (level: string) => `/levels/${level.toLowerCase()}/reading`,
  levelWriting: (level: string) => `/levels/${level.toLowerCase()}/writing`,
  levelSpeaking: (level: string) => `/levels/${level.toLowerCase()}/speaking`,
  levelListening: (level: string) => `/levels/${level.toLowerCase()}/listening`,
  lesson: (id: string) => `/lesson/${id}`,
  quiz: (id: string) => `/quiz/${id}`,
  review: '/review',
  vocabulary: (id: string) => `/vocabulary/${id}`,
  profile: '/profile',
  stats: '/stats',
  achievements: '/achievements',
} as const
