#!/usr/bin/env tsx
/**
 * Reads the active theme and writes CSS variable overrides into globals.css.
 * Run after any theme change: `npx tsx scripts/generate-css-vars.ts`
 *
 * This is the bridge between src/design-system/ (JS) and the CSS/shadcn layer.
 * Changing the theme file → run this script → entire app re-themes.
 */
import { writeFileSync, readFileSync } from 'fs'
import { join } from 'path'

// Inline the theme values to avoid ESM import issues in a script
const theme = {
  background: '#F7F4EF',
  backgroundDark: '#1A1814',
  surface: '#FFFFFF',
  surfaceDark: '#242019',
  textPrimary: '#1E1B16',
  textMuted: '#6B6460',
  primary: '#C24E2A',
  primaryHover: '#A03D20',
  secondary: '#3D5166',
  xp: '#D4970A',
  correct: '#2F7D52',
  wrong: '#9B2335',
}

// Convert hex to HSL for shadcn CSS variable format
function hexToHsl(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16) / 255
  const g = parseInt(hex.slice(3, 5), 16) / 255
  const b = parseInt(hex.slice(5, 7), 16) / 255

  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  let h = 0
  let s = 0
  const l = (max + min) / 2

  if (max !== min) {
    const d = max - min
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) / 6
        break
      case g:
        h = ((b - r) / d + 2) / 6
        break
      case b:
        h = ((r - g) / d + 4) / 6
        break
    }
  }

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`
}

const cssVars = `/* AUTO-GENERATED by scripts/generate-css-vars.ts — do not edit manually */
/* To retheme: edit src/design-system/themes/cafe-lumiere.ts then re-run the script */
@layer base {
  :root {
    --background: ${hexToHsl(theme.background)};
    --foreground: ${hexToHsl(theme.textPrimary)};
    --card: 0 0% 100%;
    --card-foreground: ${hexToHsl(theme.textPrimary)};
    --popover: 0 0% 100%;
    --popover-foreground: ${hexToHsl(theme.textPrimary)};
    --primary: ${hexToHsl(theme.primary)};
    --primary-foreground: 0 0% 100%;
    --secondary: ${hexToHsl(theme.secondary)};
    --secondary-foreground: 0 0% 100%;
    --muted: ${hexToHsl(theme.textMuted)};
    --muted-foreground: ${hexToHsl(theme.textMuted)};
    --accent: ${hexToHsl(theme.xp)};
    --accent-foreground: ${hexToHsl(theme.textPrimary)};
    --destructive: ${hexToHsl(theme.wrong)};
    --destructive-foreground: 0 0% 100%;
    --border: 35 15% 88%;
    --input: 35 15% 88%;
    --ring: ${hexToHsl(theme.primary)};
    --radius: 0.75rem;
    --chart-1: ${hexToHsl(theme.primary)};
    --chart-2: ${hexToHsl(theme.correct)};
    --chart-3: ${hexToHsl(theme.xp)};
    --chart-4: ${hexToHsl(theme.secondary)};
    --chart-5: ${hexToHsl(theme.wrong)};
  }

  .dark {
    --background: ${hexToHsl(theme.backgroundDark)};
    --foreground: 35 8% 94%;
    --card: 35 8% 13%;
    --card-foreground: 35 8% 94%;
    --popover: 35 8% 13%;
    --popover-foreground: 35 8% 94%;
    --primary: ${hexToHsl(theme.primary)};
    --primary-foreground: 0 0% 100%;
    --secondary: ${hexToHsl(theme.secondary)};
    --secondary-foreground: 0 0% 100%;
    --muted: 35 8% 45%;
    --muted-foreground: 35 8% 65%;
    --accent: ${hexToHsl(theme.xp)};
    --accent-foreground: 35 8% 10%;
    --destructive: ${hexToHsl(theme.wrong)};
    --destructive-foreground: 0 0% 100%;
    --border: 35 8% 20%;
    --input: 35 8% 20%;
    --ring: ${hexToHsl(theme.primary)};
    --chart-1: ${hexToHsl(theme.primary)};
    --chart-2: ${hexToHsl(theme.correct)};
    --chart-3: ${hexToHsl(theme.xp)};
    --chart-4: ${hexToHsl(theme.secondary)};
    --chart-5: ${hexToHsl(theme.wrong)};
  }
}
`

const globalsPath = join(process.cwd(), 'src/app/globals.css')
const existing = readFileSync(globalsPath, 'utf8')

// Remove any previous auto-generated block
const withoutGenerated = existing.replace(
  /\/\* AUTO-GENERATED[\s\S]*?(?=@layer base \{[\s\S]*?html)/,
  '',
)

// Prepend the new generated block after the first @import/@tailwind line
const firstLayerIndex = withoutGenerated.indexOf('@layer base {')
const before = withoutGenerated.slice(0, firstLayerIndex)
const after = withoutGenerated.slice(firstLayerIndex)

writeFileSync(globalsPath, before + cssVars + '\n' + after)
console.log('✓ CSS variables written to src/app/globals.css')
console.log('  Active theme: Café Lumière')
